# Generated by Django 2.1.3 on 2019-01-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gohome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
